on: [workflow_dispatch]

name: Conformance Suite

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  conformance:
    name: Check sigstore conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Rustup
        run: |
          rustup install --profile minimal stable
          rustup override set stable
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - run: |
          cargo build --manifest-path=tests/conformance/Cargo.toml
      - uses: sigstore/sigstore-conformance@main
        with:
          entrypoint: ${{ github.workspace }}/tests/conformance/target/debug/sigstore
